title: <p align="center">Pat BALDOMAR</p>
logo: /assets/img/Paterno.jpg
description: 
  <p align="center">
  <a href="/another-page.html"><img alt="Static Badge" src="https://img.shields.io/badge/GitHub-Entry%20Level%20Data%20Analyst-green"></a>  
  <a href="https://in.linkedin.com/in/patab"><img alt="Static Badge" src="https://img.shields.io/badge/BIM%20CAD%20Designer-LinkedIn-blue"></a>
  <br>
  CONTACT INFORMATION
  <br>
  email ~ <a href="mailto:paterno.baldomar@gmail.com">paterno.baldomar@gmail.com</a>
  <br>
  phone ~ +639563723553
  <hr />
  Self-driven individual, always confident and eager to learn new things. Independent yet collaborative in exchanging idea towards a common goal. Ability to connect effectively with other individuals. Creative and innovative with great analytical thinking.
  </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
